require("plugins-setup")
require("core.colorscheme")
require("core.options")
require("core.keymaps")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.lsp")

